[project]
name = "arca-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firebase-admin>=7.1.0",
    "natal>=0.9.6",
    "rich>=14.2.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
]
